name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Configurar credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload JAR to S3
        run: |
          aws s3 cp target/feedback-1.0.0-SNAPSHOT-aws.jar \
            s3://feedback-app-beatriz/feedback-1.0.0-SNAPSHOT-aws.jar \
           --region us-east-2

      - name: Deploy Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name feedback \
            --s3-bucket feedback-app-beatriz \
            --s3-key feedback-1.0.0-SNAPSHOT-aws.jar \
            --region us-east-2

      - name: Wait until Lambda is updated 
        run: aws lambda wait function-updated 
                --function-name feedback 
                --region us-east-2

      - name: Update Lambda configuration with Layer
        run: |
          aws lambda update-function-configuration \
            --function-name feedback \
            --runtime java21 \
            --handler com.feedback.lambda.StreamLambdaHandler::handleRequest \
            --layers arn:aws:lambda:us-east-2:877352799066:layer:postgresql-sns-layer:1 \
            --region us-east-2
