name: Deploy Lambda Feedback

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do c√≥digo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # 5. Deploy direto para Lambda
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name feedback \
            --zip-file fileb://target/feedback-1.0.0-SNAPSHOT-aws.jar \
            --region us-east-2

          aws lambda update-function-configuration \
            --function-name feedback \
            --runtime java21 \
            --handler com.feedback.lambda.StreamLambdaHandler::handleRequest \
            --layers arn:aws:lambda:us-east-2:877352799066:layer:postgresql-sns-layer:1  
            --region us-east-2


