name: Deploy Lambda Feedback

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup do Java (Java 21, para compilar seu projeto)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Build com Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Configurar credenciais AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2   # região da sua Lambda

      # 5. Deploy da Lambda
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: feedback
          zip-file: target/feedback-1.0.0-SNAPSHOT-aws.jar
          aws-region: us-east-2
          handler: com.feedback.lambda.StreamLambdaHandler::handleRequest
          runtime: java21
          dry-run: false
